### ISSUE TITLE
重制API后软件无法使用

### ISSUE THREAD

**Issue by topgary** [geekdada/PopClip-Extensions#1]
重制过一次API后，软件就无法使用了，试过重新安装、重启软件都不行。

**Comment by geekdada** [comment]
设置里填入新的 API 还是不行？

**Comment by topgary** [comment]
嗯，重新填写了也不行

**Comment by geekdada** [comment]
试试重启一下 popclip

**Comment by topgary** [comment]
都不行，也重新安装过插件，也是不行😂

**Comment by geekdada** [comment]
应该不是插件的问题

**Comment by geekdada** [comment]
新的 API 在别的地方能用吗

**Comment by topgary** [comment]
API在其他地方都可以用，找少楠看过

**Comment by geekdada** [comment]
我试了修改 API 是有效的……

**Comment by topgary** [comment]
使用了cdn的原因吗？ 我utools的插件也是这个情况，修改过API后不能保存，那个作者核查了是使用了cdn的原因

**Comment by geekdada** [comment]
CDN? 你可能要找 flomo 的朋友看一下
