### ISSUE TITLE
好像没法使用了

### ISSUE THREAD

**Issue by Graning** [geekdada/PopClip-Extensions#3]

**Comment by geekdada** [comment]
可以使用，请贴一下错误

**Comment by hezhonghao** [comment]
和popclip的连接出了问题。再网页尝试贴内容到flomo的时候，正常情况下会弹出“✅”，但最近一直弹出“❌”。

似乎和popclip 此次更新有关https://pilotmoon.com/blog/2021/09/15/popclip-macos-monterey#fn:2
但我不是很肯定，因为我遇到同样的问题，可我的系统不是macOS Monterey

最早一次出问题如链接中图片所示，后来就没有修复过。

**Comment by geekdada** [comment]
@Graning @NeptuneBlank 请试试最新版本。

**Comment by Graning** [comment]
最新版本已经解决了，感谢

**Comment by hezhonghao** [comment]
感谢！

Gran ***@***.***>于2021年10月20日 周三15:06写道：
