### ISSUE TITLE
安装时显示错误

### ISSUE THREAD

**Issue by hsy505** [geekdada/PopClip-Extensions#4]
<img width="247" alt="截屏2021-11-02 下午3 36 47" src="https://user-images.githubusercontent.com/2184605/139804790-9905f27e-28d5-4b6f-9604-e659c4edc30f.png">
显示如图，和安装了 Monterey 有关？

**Comment by geekdada** [comment]
新版本已修复，请更新。

Popclip 最近的更新在不停地破坏兼容性。
