### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Xinkai-Huang** [geekdada/PopClip-Extensions#7]
大佬，安装popclip插件、填写自己的cubox API链接后，无论发送链接和文本速记，都提示一个x
看Readme中说依赖命令行工具，这个有针对小白的使用教程吗（flomo的插件填入API链接后即可正常使用）

**Comment by iRubbish** [comment]
工具我也安装了，还是不行
手动执行命令行工具是正常使用的，好奇怪

**Comment by geekdada** [comment]
请根据这里的步骤试试重装一次插件 https://github.com/geekdada/PopClip-Extensions#macos-13-%E5%8F%8A%E4%B9%8B%E5%90%8E

**Comment by iRubbish** [comment]
> 请根据这里的步骤试试重装一次插件 https://github.com/geekdada/PopClip-Extensions#macos-13-%E5%8F%8A%E4%B9%8B%E5%90%8E

尝试过了还是不行，不过我自己手写了一个已解决自己的需求了。感谢大佬回复
