### ISSUE TITLE
popclip插件无法正常使用

### ISSUE THREAD

**Issue by BENZEMA216** [geekdada/PopClip-Extensions#8]
点击popclip操作icon后，loading态以“X”结束
<img width="341" alt="image" src="https://user-images.githubusercontent.com/43908081/230547623-67b617ac-aee7-475c-b488-cb88b04a05b7.png">

**Comment by BENZEMA216** [comment]
<img width="374" alt="image" src="https://user-images.githubusercontent.com/43908081/230547791-7edfa723-3234-4e2a-a651-29198ef30143.png">

**Comment by iRubbish** [comment]
我也是这样
Mac14系统

**Comment by geekdada** [comment]
请根据这里的步骤试试重装一次插件 https://github.com/geekdada/PopClip-Extensions#macos-13-%E5%8F%8A%E4%B9%8B%E5%90%8E
